Moved internal functions into external functions (and external files). Updated documentation. Added a Makefile for easy installation, syntax checking, uninstallation. Added new functionality with the external function files.

diff --git a/freewrite b/freewrite
--- a/freewrite
+++ b/freewrite
@@ -1,7 +1,11 @@
 #!/bin/bash
 
 #
-# freewrite -- A script to simple the freewriting process.
+# freewrite
+#
+#	A script to simple the freewriting process.
+# 
+# Keith A. Watson <ikawnoclast@gmail.com>
 #
 
 umask 022
@@ -9,67 +13,97 @@ umask 022
 # USER CONFIGURAGLE OPTIONS
 dropbox_dir="$HOME/Dropbox"
 fw_store="$dropbox_dir/Writing/Freewriting"
-fw_file_path="$fw_store/`date '+%Y/%m/%d.txt'`"
-txt_date=`date '+%A, %B %d, %Y \(week %V\) %H:%M'`
+txt_date=$(date '+%A, %B %d, %Y \(week %V\) %H:%M')
 template_file="$fw_store/template.txt"
 fw_editor="/usr/local/bin/emacs"
 fw_editor_opts=""
+
 time=$(( 30 * 60 )) # time in seconds
 
 # ADVANCED CONFIGURATION OPTIONS
-fw_file_path="$fw_store/`date '+%Y/%m/%d.txt'`"
-txt_date=`date '+%A, %B %d, %Y \(week %V\) %H:%M'`
+file_prefix=$(date '+%Y/%m/%d')
+session_file="$fw_store/$file_prefix.txt"
+data_file="$fw_store/$file_prefix-data.txt"
+txt_date=$(date '+%A, %B %d, %Y \(week %V\) %H:%M')
+before_function_list="before_check_directories before_check_if_file_exists before_create_session_file before_query_mood before_get_weather"
+during_function_list="during_wait_and_say"
+after_function_list="after_print_word_count after_append_timestamp after_find_todos after_print_final_message"
 
-# check and create directories and destination file
-fw_base_dir=`dirname $fw_file_path`
-if [ ! -d $dropbox_dir ]; then
-	echo "$0: Dropbox directory \"$dropbox_dir\" is missing. Exiting!"
-	exit 1
-fi
-if [ -f $fw_file_path ]; then
-	echo "$0: Free writing file \"$fw_file_path\" exists. Exiting!"
-	exit 1
-fi
-[ ! -d $fw_base_dir ] && mkdir -p $fw_base_dir
-sed -e "s/%%DATE_FIELD%%/$txt_date/" < $template_file > $fw_file_path
+# determine script storage directory
+_source="${BASH_SOURCE[0]}"
+while [ -h "$_source" ] ; do _source="$(readlink "$_source")"; done
+_script_dir="$( cd -P "$( dirname "$_source" )" && pwd )"
+
+# parse command line arguments
+_safe_mode="no"
+_debug_mode="no"
+while getopts ":hs" opt; do
+	case $opt in
+		h)
+		echo "$0 [-h] [-s]" >&2
+		echo -e "\t-h\tThis help message." >&2
+		echo -e "\t-s\tSafe mode. Does not use any functions." >&2
+		echo -e "\t-d\tDebug mode. Provides additional output." >&2
+		exit 0
+		;;
+		s)
+		_safe_mode="yes"
+		;;
+		d)
+		_debug_mode="yes"
+		;;
+		\?)
+      	echo "Invalid option: -$OPTARG" >&2
+      	;;
+  	esac
+done
+
+echo -e "debug_mode: $_debug_mode\nsafe_mode: $_safe_mode" >> $data_file
+
+_execute_function_list () {
+	[ $_safe_mode == "yes" ] && return
+	local ext_function_list="$1"
+
+	for ext_function in $ext_function_list; do
+		$ext_function
+		if [ $? -ne 0 ]; then
+			echo "$0: $ext_function returned an error. Exiting."
+			exit 1
+		fi
+	done
+}
+
+_load_external_functions () {
+	[ $_safe_mode == "yes" ] && return
+	local function_types="before during after"
+	
+	for function_type in $function_types; do
+		for ext_function_file in $_script_dir/${function_type}_* ; do
+			[ -r $ext_function_file ] && source $ext_function_file
+		done
+	done
+}
+
+_terminate_bg_jobs () {
+	for job in $(jobs -p); do 
+		kill $job; 
+	done
+}
+
+# kill any background jobs exiting on various signals
+trap "_terminate_bg_jobs" EXIT QUIT HUP INT
+
+_load_external_functions
+_execute_function_list "$before_function_list"
+_execute_function_list "$during_function_list"
 
 # calculate the lines in the file to jump the editor to the end to start
-jump_to=`wc -l $fw_file_path | awk '{print $1}'`
-
-# calculate the template word count for later use in determining total
-#  word count
-template_word_count=`wc -w $fw_file_path | awk '{print $1}'`
-
-# start a timer in subshell to run independently of the editor
-( sleep $time && say "Free writing session has ended" ) &
+jump_to=$(wc -l $session_file | awk '{print $1}')
 
 # open an editor with a template and dated filename
-$fw_editor +$jump_to $fw_editor_opts $fw_file_path
+$fw_editor +$jump_to $fw_editor_opts $session_file
 
-# grep for todo entries for extraction
-todo_list=`mktemp /tmp/todos.XXXXXXXX`
-grep "^TODO:" $fw_file_path > $todo_list
-if [ -s $todo_list ]; then
-	echo "The following to-dos were extracted from the text:"
-	cat $todo_list
-	echo
-	rm -f $todo_list
-fi
-
-# calculate a final word count
-fw_file_word_count=`wc -w $fw_file_path | awk '{print $1}'`
-final_word_count=$(( fw_file_word_count - template_word_count ))
-
-# add a completion timestamp to the end of the file
-date_completed=`date '+%H:%M'`
-cat <<__EOT__ >> $fw_file_path
-
----------------------------------------------------------------------------
-Completed at: $date_completed
-__EOT__
-
-# exit with encouraging words?
-echo "You wrote $final_word_count words."
-echo "Thanks for another awesome free writing session!"
+# run functions after the free write session
+_execute_function_list "$after_function_list"
 
 exit 0
